### ISSUE TITLE
Support installing "bleeding edge" SDKs

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/setup-dart#4]
Support installing "bleeding edge" builds from http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/

One question is what is a good name for these?

1. Bleeding edge (don't love the word "bleeding")
1. Latest (potentially confusing with "latest" from a channel)
1. Nightlies (although these are not nightly builds)

**Comment by athomas** [comment]
I would prefer if we treat channels as branch names rather than a different namespace. For `dev`, `beta` and `stable` that is already true. We used `be` because it sorts alphabetically before `dev` but that is no longer important with the new versioning scheme. So can use `main` (anticipating the future name of the Dart SDK default branch). Then we can remove the be/Bleeding edge/edge terminology from various CI/release tooling later.

FYI, not sure if these builds will work on macOS (be builds aren't signed).

**Comment by mit-mit** [comment]
> not sure if these builds will work on macOS (be builds aren't signed).

I seem to be able to run them if I right-click on the `dart` binary, select open, and then OK to the signing warning. After this `dart` runs without warning.

**Comment by athomas** [comment]
> > not sure if these builds will work on macOS (be builds aren't signed).
> 
> I seem to be able to run them if I right-click on the `dart` binary, select open, and then OK to the signing warning. After this `dart` runs without warning.

Yes, but anything that requires user interaction doesn't sound like an option on GitHub Actions. It's something we should just try.

**Comment by mit-mit** [comment]
Ah, yes of course, had not thought of that.

**Comment by mit-mit** [comment]
@athomas about macOS and signing, I wonder if perhaps we should consider doing a single daily edge build that has signing? Would that be possible?

**Comment by athomas** [comment]
I'm afraid we will have to re-do parts of our signing infra to do more signed builds. We may be hitting hard limits and be unable to sign other releases if we use what we have excessively.

**Comment by kevmoo** [comment]
https://github.com/google/mono_repo.dart/pull/299

FYI – so we cannot migrate mono repo here (yet) because of this!

CC @jakemac53

**Comment by mit-mit** [comment]
Attempted fix in https://github.com/dart-lang/setup-dart/pull/16

**Comment by mit-mit** [comment]
Now available in `dart-lang/setup-dart@v0.3`
