### ISSUE TITLE
Support multiple platform architectures

### ISSUE THREAD

**Issue by timsneath** [dart-lang/setup-dart#9]
With Apple Silicon and Windows-on-ARM coming, as well as existing 32-bit variants, we probably shouldn't hardcode the architecture. See, for example, https://github.com/cedx/setup-dart

**Comment by mit-mit** [comment]
The main action script (`setup.sh`) actually supports it via a fourth parameter. It's just not exposed in the action yet, as I havn't found a way of running Actions jobs on ia32, so I can't test it.

@athomas do you know if this is possible?

**Comment by timsneath** [comment]
I don't think we need to install on a Windows 32-bit machine, if that's what you're asking. For my own (selfish) purposes at least, it would be a step forward to be able to install Dart 32-bit on a 64-bit machine, which would enable me to test that my code runs on 32-bit architectures.

**Comment by athomas** [comment]
Yes, on Windows we can run the 32-bit Dart binary. Judging from [this](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/minimum-hardware-requirements-overview#31-processor) that will remain the case for some years to come.

Furthermore, you can use your own hardware on GitHub Actions (and that could be a bare metal machine rather than a cloud VM) which may be something folks will want to use.

Regarding testing, we can test that the action downloads the right SDK without running it for architectures we don't have runners for (e.g. by comparing a hash of the dart binary on a fixed version, or by making the action download the SHA256 checksum file as well and storing it somewhere we can compare it to the expected checksum).

**Comment by mit-mit** [comment]
Now available as `dart-lang/setup-dart@v0.4`
